# Generated by Django 3.1.1 on 2020-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='address',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='information',
            name='arabicLanguage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='city',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='information',
            name='education',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='information',
            name='englishLanguage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='fisically',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='information',
            name='province',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='information',
            name='religousEducation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='information',
            name='studentNumber',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
